#!/bin/bash

set -e

cpu_nb="$1"
[ "$cpu_nb" = "" ] && cpu_nb=4

mkdir -p output_top
cp -rfL src/* output_top
cd output_top

verilator --binary -j 0                         \
  +define+MULTISIM                              \
  top.sv memory.sv cpu_multisim_server.sv       \
  +incdir+$MULTISIM_SRC/core                    \
  $MULTISIM_SRC/core/multisim_server_push.sv    \
  $MULTISIM_SRC/core/multisim_server_pull.sv    \
  +incdir+$MULTISIM_SRC/apb                     \
  $MULTISIM_SRC/apb/multisim_server_apb_pull.sv \
  $MULTISIM_SRC/core/multisim_server.cpp        \
  $MULTISIM_SRC/core/socket_server/server.cpp   \
  -GCPU_NB=$cpu_nb # --trace --trace-structs
cat << EOF

----------------------------------------
-- simulation start
----------------------------------------
EOF
time ./obj_dir/Vtop
