#!/bin/bash

cpu_nb="$1"
[ "$cpu_nb" = "" ] && cpu_nb=4

# on exit, send SIGTERM to all the processes in the foreground process group,
# this allows for a clean termination of the clients
exit_clean=0
send_sigterm_to_process_group() {
  if ((exit_clean != 1)); then
    echo "Send SIGTERM to process group"
    kill -SIGTERM -$$
  fi
}
trap send_sigterm_to_process_group EXIT

# 1- clean server files
rm -rf output_top/.multisim

# 2- start clients
for ((i=0;i<cpu_nb;i++)); do
  ./run_cpu $i &
done

# 3- start server
./run_top $cpu_nb

exit_clean=1
