#!/bin/bash

cpu_nb="$1"
extra_dummy_channels="$2"

[ "$cpu_nb" = "" ] && cpu_nb=4
[ "$extra_dummy_channels" = "" ] && extra_dummy_channels=0

# change ulimit to avoid libc crash
ulimit_factor=$(((cpu_nb + 15) / 16))
ulimit -s $((ulimit_factor * 8192)) # stack size in kB
ulimit -u $((ulimit_factor * 4096)) # max user processes

# 1- clean server files
rm -f output_top/server_*.txt
rm -f output_top/server_exit

# 2- start clients
# -- compilation
./run_cpu compilation 0 $extra_dummy_channels  > /dev/null
for ((i=1;i<cpu_nb;i++)); do
  rm -rf output_cpu_$i
  cp -rf output_cpu_0 output_cpu_$i
done
# -- run
for ((i=0;i<cpu_nb;i++)); do
  ./run_cpu run $i &
done

# 3- start server
./run_top $cpu_nb $extra_dummy_channels
