#!/bin/bash

set -e

cpu_nb="$1"
extra_dummy_channels="$2"

[ "$cpu_nb" = "" ] && cpu_nb=4
[ "$extra_dummy_channels" = "" ] && extra_dummy_channels=0

mkdir -p output_top
cp -rfL src/* output_top
cd output_top

verilator --binary -j 0                                                    \
  +define+MULTISIM                                                         \
  top.sv noc.sv cpu_multisim_server.sv                                     \
  +incdir+$MULTISIM_SRC                                                    \
  $MULTISIM_SRC/multisim_server_push.sv                                    \
  $MULTISIM_SRC/multisim_server_pull.sv                                    \
  $MULTISIM_SRC/multisim_server.cpp $MULTISIM_SRC/socket_server/server.cpp \
  -GCPU_NB=$cpu_nb -GEXTRA_DUMMY_CHANNELS=$extra_dummy_channels
cat << EOF

----------------------------------------
-- simulation start
----------------------------------------
EOF
time ./obj_dir/Vtop
